### ISSUE TITLE
app.py - ModuleNotFoundError: No module named 'mysql'

### ISSUE THREAD

**Issue by ShowCreate** [ShowCreate/useful-information#2]
app.py를 실행할 때 다음과 같은 오류 메세지가 나타납니다.
MySQL은 분명히 컴퓨터에 설치가 되어 있는데 어떻게 해결해야 되는지 궁금합니다.
`
Traceback (most recent call last):
  File "C:\Users\JeongIn\Desktop\useful-information\OpensSource_sofware_project\app.py", line 2, in <module>
    from static.db.db import get_db_connection
  File "C:\Users\JeongIn\Desktop\useful-information\OpensSource_sofware_project\static\db\db.py", line 1, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
`

commit 정보: 831f562
@Pyochangwoo

**Comment by Pyochangwoo** [comment]
get_db_connection 이라는 모듈이 설치가 안되어서 오류가 생긴것 같습니다. 
pip install get_db_connection 명령어로 모듈을 설치하면 해결됩니다
